print('Programa de cálculo de área')
num1=int(input('Qual é o comprimento do terreno? '))
num2=int(input('Qual é a largura do terreno? '))
area=int(num1)*int(num2)
print('A área do terreno é de: ',area,'m²')
